# Generated by Django 5.2.4 on 2025-07-21 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testdata', models.JSONField(default=list)),
                ('position1_mark', models.IntegerField(default=0)),
                ('position2_mark', models.IntegerField(default=0)),
                ('position3_mark', models.IntegerField(default=0)),
                ('classid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='test', to='classes.scheduledclass')),
                ('position1_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='position1_tests', to=settings.AUTH_USER_MODEL)),
                ('position2_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='position2_tests', to=settings.AUTH_USER_MODEL)),
                ('position3_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='position3_tests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
