# Generated by Django 5.2.4 on 2025-07-20 13:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute', models.CharField(max_length=255)),
                ('classname', models.CharField(max_length=255)),
                ('timeStart', models.CharField(max_length=20)),
                ('timeEnd', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('takenBy', models.CharField(max_length=255)),
                ('venue', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('not started', 'Not Started'), ('started', 'Started'), ('end', 'Ended')], default='not started', max_length=20)),
                ('students', models.ManyToManyField(blank=True, related_name='scheduled_classes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
